name: online_rockpaperscissor
description: interesting game

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - stuffs/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Ranchers
      fonts:
        - asset: stuffs/Ranchers-Regular.ttf

    - family: Staatliches
      fonts:
        - asset: stuffs/Staatliches-Regular.ttf
